### ISSUE TITLE
Segmentation fault in match_multi_number

### ISSUE THREAD

**Issue by nlaplante** [thatguystone/approxidate#1]
approxidate.c line 409. For input string "1/1/2014"

**Comment by nlaplante** [comment]
Nevermind. Issue must be in my Vala code. Test runs fine with specified string.

**Comment by nlaplante** [comment]
After some tests, "1/1/2014" seems to really cause problems. Reopening this. Is "1/1/2014" a valid value in  approxidate's  scope?

**Comment by thatguystone** [comment]
Weird. Github never notified me of this issue.

Either way, I've pushed a test case for 1/1/2014, and that date works fine for me. Could you test it out and let me know what you see?

**Comment by thatguystone** [comment]
I'm guessing this isn't an issue anymore. Feel free to reopen if you run into any other problems.
