### ISSUE TITLE
Inconsistent epoch values for the same string

### ISSUE THREAD

**Issue by DackJempsey** [thatguystone/approxidate#3]
**Python Library**
When inputing a string of: '9/15/2019'  you will get different results based on the time of 'query'. Seems that the output is relative to the time of input. 
I believe that the output should be consistent. 

<img width="364" alt="Screen Shot 2020-01-20 at 5 18 52 PM" src="https://user-images.githubusercontent.com/23224399/72761140-06558080-3ba9-11ea-82f3-43ebbf932190.png">

Haven't done c in a while but might get back into it with a PR for this if you'r willing. Can make it so that it takes flag/kwarg

**Comment by thatguystone** [comment]
That sounds pretty reasonable (that's actually how  [approxidate_relative](https://github.com/git/git/blob/5fa0f5238b0cd46cfe7f6fa76c3f526ea98148d9/date.c#L1291) used to behave), but I just never brought over the functionality. How does something like this sound?

```python
def approx(date: str, relative_to: Union[datetime.date, datetime.datetime, float, None]=None) -> float
```

Using None would maintain the current behavior, and then, for your case, you could pass in a time to parse relative to.

**Comment by DackJempsey** [comment]
Yea that sounds perfect. 

Thanks,
Jack
