### ISSUE TITLE
Add a small cache to speed up redundant calls

### ISSUE THREAD

**Issue by avylove** [thatguystone/approxidate#4]
Very useful library!

I've found there are some cases where I can't avoid calling `approx()` with the same data more than once.  I think adding a small cache may be useful similar to the way the `re` library does. While `approx()` is fast, it would be good to avoid unnecessary processing.

This could be as simple as adding the lru_cache decorator.

```
@functools.lru_cache(maxsize=64)
def approx(date: str, *, relative_to: DateType = None) -> float:
```

**Comment by thatguystone** [comment]
I'm not sure adding caching is a good idea here. If your app is bottle-necking on approx, then you might consider adding a wrapper in your app that does the caching.

**Comment by avylove** [comment]
It's definitely not bottlenecking. It's really more that functions like this tend to get called on the same data multiple times in quick succession. You could say that's on the user, but often it's out of the user's control.
